// List of cities
export const cities = [
  { city: 'New York City', state: 'New York' },
  { city: 'Los Angeles', state: 'California' },
  { city: 'Chicago', state: 'Illinois' },
  { city: 'Houston', state: 'Texas' },
  { city: 'Phoenix', state: 'Arizona' },
  { city: 'Philadelphia', state: 'Pennsylvania' },
  { city: 'San Antonio', state: 'Texas' },
  { city: 'San Diego', state: 'California' },
  { city: 'Dallas', state: 'Texas' },
  { city: 'San Jose', state: 'California' },
  { city: 'Austin', state: 'Texas' },
  { city: 'Jacksonville', state: 'Florida' },
  { city: 'Fort Worth', state: 'Texas' },
  { city: 'Columbus', state: 'Ohio' },
  { city: 'Charlotte', state: 'North Carolina' },
  { city: 'San Francisco', state: 'California' },
  { city: 'Indianapolis', state: 'Indiana' },
  { city: 'Seattle', state: 'Washington' },
  { city: 'Denver', state: 'Colorado' },
  { city: 'Washington	District of Columbia', state: 'DC' },
  { city: 'Boston', state: 'Massachusetts' },
  { city: 'El Paso', state: 'Texas' },
  { city: 'Nashville', state: 'Tennessee' },
  { city: 'Detroit', state: 'Michigan' },
  { city: 'Oklahoma City', state: 'Oklahoma' },
  { city: 'Portland', state: 'Oregon' },
  { city: 'Las Vegas', state: 'Nevada' },
  { city: 'Memphis', state: 'Tennessee' },
  { city: 'Louisville', state: 'Kentucky' },
  { city: 'Baltimore', state: 'Maryland' },
  { city: 'Milwaukee', state: 'Wisconsin' },
  { city: 'Albuquerque', state: 'New Mexico' },
  { city: 'Tucson', state: 'Arizona' },
  { city: 'Fresno', state: 'California' },
  { city: 'Mesa', state: 'Arizona' },
  { city: 'Sacramento', state: 'California' },
  { city: 'Atlanta', state: 'Georgia' },
  { city: 'Kansas City', state: 'Missouri' },
  { city: 'Colorado Springs', state: 'Colorado' },
  { city: 'Omaha', state: 'Nebraska' },
  { city: 'Raleigh', state: 'North Carolina' },
  { city: 'Miami', state: 'Florida' },
  { city: 'Long Beach', state: 'California' },
  { city: 'Virginia Beach', state: 'Virginia' },
  { city: 'Oakland', state: 'California' },
  { city: 'Minneapolis', state: 'Minnesota' },
  { city: 'Tulsa', state: 'Oklahoma' },
  { city: 'Tampa', state: 'Florida' },
  { city: 'Arlington', state: 'Texas' },
  { city: 'New Orleans', state: 'Louisiana' },
  { city: 'Wichita', state: 'Kansas' },
  { city: 'Bakersfield', state: 'California' },
  { city: 'Cleveland', state: 'Ohio' },
  { city: 'Aurora', state: 'Colorado' },
  { city: 'Anaheim', state: 'California' },
  { city: 'Honolulu', state: 'Hawaii' },
  { city: 'Santa Ana', state: 'California' },
  { city: 'Riverside', state: 'California' },
  { city: 'Corpus Christi', state: 'Texas' },
  { city: 'Lexington', state: 'Kentucky' },
  { city: 'Henderson', state: 'Nevada' },
  { city: 'Stockton', state: 'California' },
  { city: 'Saint Paul', state: 'Minnesota' },
  { city: 'Cincinnati', state: 'Ohio' },
  { city: 'St. Louis', state: 'Missouri' },
  { city: 'Pittsburgh', state: 'Pennsylvania' },
  { city: 'Greensboro', state: 'North Carolina' },
  { city: 'Lincoln', state: 'Nebraska' },
  { city: 'Anchorage', state: 'Alaska' },
  { city: 'Plano', state: 'Texas' },
  { city: 'Orlando', state: 'Florida' },
  { city: 'Irvine', state: 'California' },
  { city: 'Newark', state: 'New Jersey' },
  { city: 'Durham', state: 'North Carolina' },
  { city: 'Chula Vista', state: 'California' },
  { city: 'Toledo', state: 'Ohio' },
  { city: 'Fort Wayne', state: 'Indiana' },
  { city: 'St. Petersburg', state: 'Florida' },
  { city: 'Laredo', state: 'Texas' },
  { city: 'Jersey City', state: 'New Jersey' },
  { city: 'Chandler', state: 'Arizona' },
  { city: 'Madison', state: 'Wisconsin' },
  { city: 'Lubbock', state: 'Texas' },
  { city: 'Scottsdale', state: 'Arizona' },
  { city: 'Reno', state: 'Nevada' },
  { city: 'Buffalo', state: 'New York' },
  { city: 'Gilbert', state: 'Arizona' },
  { city: 'Glendale', state: 'Arizona' },
  { city: 'North Las Vegas', state: 'Nevada' },
  { city: 'Winston–Salem', state: 'North Carolina' },
  { city: 'Chesapeake', state: 'Virginia' },
  { city: 'Norfolk', state: 'Virginia' },
  { city: 'Fremont', state: 'California' },
  { city: 'Garland', state: 'Texas' },
  { city: 'Irving', state: 'Texas' },
  { city: 'Hialeah', state: 'Florida' },
  { city: 'Richmond', state: 'Virginia' },
  { city: 'Boise', state: 'Idaho' },
  { city: 'Spokane', state: 'Washington' },
  { city: 'Baton Rouge', state: 'Louisiana' },
  { city: 'Tacoma', state: 'Washington' },
  { city: 'San Bernardino', state: 'California' },
  { city: 'Modesto', state: 'California' },
  { city: 'Fontana', state: 'California' },
  { city: 'Des Moines', state: 'Iowa' },
  { city: 'Moreno Valley', state: 'California' },
  { city: 'Santa Clarita', state: 'California' },
  { city: 'Fayetteville', state: 'North Carolina' },
  { city: 'Birmingham', state: 'Alabama' },
  { city: 'Oxnard', state: 'California' },
  { city: 'Rochester', state: 'New York' },
  { city: 'Port St. Lucie', state: 'Florida' },
  { city: 'Grand Rapids', state: 'Michigan' },
  { city: 'Huntsville', state: 'Alabama' },
  { city: 'Salt Lake City', state: 'Utah' },
  { city: 'Frisco', state: 'Texas' },
  { city: 'Yonkers', state: 'New York' },
  { city: 'Amarillo', state: 'Texas' },
  { city: 'Glendale', state: 'California' },
  { city: 'Huntington Beach', state: 'California' },
  { city: 'McKinney', state: 'Texas' },
  { city: 'Montgomery', state: 'Alabama' },
  { city: 'Augusta', state: 'Georgia' },
  { city: 'Aurora', state: 'Illinois' },
  { city: 'Akron', state: 'Ohio' },
  { city: 'Little Rock', state: 'Arkansas' },
  { city: 'Tempe', state: 'Arizona' },
  { city: 'Columbus', state: 'Georgia' },
  { city: 'Overland Park', state: 'Kansas' },
  { city: 'Grand Prairie', state: 'Texas' },
  { city: 'Tallahassee', state: 'Florida' },
  { city: 'Cape Coral', state: 'Florida' },
  { city: 'Mobile', state: 'Alabama' },
  { city: 'Knoxville', state: 'Tennessee' },
  { city: 'Shreveport', state: 'Louisiana' },
  { city: 'Worcester', state: 'Massachusetts' },
  { city: 'Ontario', state: 'California' },
  { city: 'Vancouver', state: 'Washington' },
  { city: 'Sioux Falls', state: 'South Dakota' },
  { city: 'Chattanooga', state: 'Tennessee' },
  { city: 'Brownsville', state: 'Texas' },
  { city: 'Fort Lauderdale', state: 'Florida' },
  { city: 'Providence', state: 'Rhode Island' },
  { city: 'Newport News', state: 'Virginia' },
  { city: 'Rancho Cucamonga', state: 'California' },
  { city: 'Santa Rosa', state: 'California' },
  { city: 'Peoria', state: 'Arizona' },
  { city: 'Oceanside', state: 'California' },
  { city: 'Elk Grove', state: 'California' },
  { city: 'Salem', state: 'Oregon' },
  { city: 'Pembroke Pines', state: 'Florida' },
  { city: 'Eugene', state: 'Oregon' },
  { city: 'Garden Grove', state: 'California' },
  { city: 'Cary', state: 'North Carolina' },
  { city: 'Fort Collins', state: 'Colorado' },
  { city: 'Corona', state: 'California' },
  { city: 'Springfield', state: 'Missouri' },
  { city: 'Jackson', state: 'Mississippi' },
  { city: 'Alexandria', state: 'Virginia' },
  { city: 'Hayward', state: 'California' },
  { city: 'Clarksville', state: 'Tennessee' },
  { city: 'Lakewood', state: 'Colorado' },
  { city: 'Lancaster', state: 'California' },
  { city: 'Salinas', state: 'California' },
  { city: 'Palmdale', state: 'California' },
  { city: 'Hollywood', state: 'Florida' },
  { city: 'Springfield', state: 'Massachusetts' },
  { city: 'Macon', state: 'Georgia' },
  { city: 'Kansas City', state: 'Kansas' },
  { city: 'Sunnyvale', state: 'California' },
  { city: 'Pomona', state: 'California' },
  { city: 'Killeen', state: 'Texas' },
  { city: 'Escondido', state: 'California' },
  { city: 'Pasadena', state: 'Texas' },
  { city: 'Naperville', state: 'Illinois' },
  { city: 'Bellevue', state: 'Washington' },
  { city: 'Joliet', state: 'Illinois' },
  { city: 'Murfreesboro', state: 'Tennessee' },
  { city: 'Midland', state: 'Texas' },
  { city: 'Rockford', state: 'Illinois' },
  { city: 'Paterson', state: 'New Jersey' },
  { city: 'Savannah', state: 'Georgia' },
  { city: 'Bridgeport', state: 'Connecticut' },
  { city: 'Torrance', state: 'California' },
  { city: 'McAllen', state: 'Texas' },
  { city: 'Syracuse', state: 'New York' },
  { city: 'Surprise', state: 'Arizona' },
  { city: 'Denton', state: 'Texas' },
  { city: 'Roseville', state: 'California' },
  { city: 'Thornton', state: 'Colorado' },
  { city: 'Miramar', state: 'Florida' },
  { city: 'Pasadena', state: 'California' },
  { city: 'Mesquite', state: 'Texas' },
  { city: 'Olathe', state: 'Kansas' },
  { city: 'Dayton', state: 'Ohio' },
  { city: 'Carrollton', state: 'Texas' },
  { city: 'Waco', state: 'Texas' },
  { city: 'Orange', state: 'California' },
  { city: 'Fullerton', state: 'California' },
  { city: 'Charleston', state: 'South Carolina' },
  { city: 'West Valley City', state: 'Utah' },
  { city: 'Visalia', state: 'California' },
  { city: 'Hampton', state: 'Virginia' },
  { city: 'Gainesville', state: 'Florida' },
  { city: 'Warren', state: 'Michigan' },
  { city: 'Coral Springs', state: 'Florida' },
  { city: 'Cedar Rapids', state: 'Iowa' },
  { city: 'Round Rock', state: 'Texas' },
  { city: 'Sterling Heights', state: 'Michigan' },
  { city: 'Kent', state: 'Washington' },
  { city: 'Columbia', state: 'South Carolina' },
  { city: 'Santa Clara', state: 'California' },
  { city: 'New Haven', state: 'Connecticut' },
  { city: 'Stamford', state: 'Connecticut' },
  { city: 'Concord', state: 'California' },
  { city: 'Elizabeth', state: 'New Jersey' },
  { city: 'Athens', state: 'Georgia' },
  { city: 'Thousand Oaks', state: 'California' },
  { city: 'Lafayette', state: 'Louisiana' },
  { city: 'Simi Valley', state: 'California' },
  { city: 'Topeka', state: 'Kansas' },
  { city: 'Norman', state: 'Oklahoma' },
  { city: 'Fargo', state: 'North Dakota' },
  { city: 'Wilmington', state: 'North Carolina' },
  { city: 'Abilene', state: 'Texas' },
  { city: 'Odessa', state: 'Texas' },
  { city: 'Columbia', state: 'Missouri' },
  { city: 'Pearland', state: 'Texas' },
  { city: 'Victorville', state: 'California' },
  { city: 'Hartford', state: 'Connecticut' },
  { city: 'Vallejo', state: 'California' },
  { city: 'Allentown', state: 'Pennsylvania' },
  { city: 'Berkeley', state: 'California' },
  { city: 'Richardson', state: 'Texas' },
  { city: 'Arvada', state: 'Colorado' },
  { city: 'Ann Arbor', state: 'Michigan' },
  { city: 'Rochester', state: 'Minnesota' },
  { city: 'Cambridge', state: 'Massachusetts' },
  { city: 'Sugar Land', state: 'Texas' },
  { city: 'Lansing', state: 'Michigan' },
  { city: 'Evansville', state: 'Indiana' },
  { city: 'College Station', state: 'Texas' },
  { city: 'Fairfield', state: 'California' },
  { city: 'Clearwater', state: 'Florida' },
  { city: 'Beaumont', state: 'Texas' },
  { city: 'Independence', state: 'Missouri' },
  { city: 'Provo', state: 'Utah' },
  { city: 'West Jordan', state: 'Utah' },
  { city: 'Murrieta', state: 'California' },
  { city: 'Palm Bay', state: 'Florida' },
  { city: 'El Monte', state: 'California' },
  { city: 'North Charleston', state: 'South Carolina' },
  { city: 'Carlsbad', state: 'California' },
  { city: 'Temecula', state: 'California' },
  { city: 'Clovis', state: 'California' },
  { city: 'Springfield', state: 'Illinois' },
  { city: 'Meridian', state: 'Idaho' },
  { city: 'Westminster', state: 'Colorado' },
  { city: 'Costa Mesa', state: 'California' },
  { city: 'High Point', state: 'North Carolina' },
  { city: 'Manchester', state: 'New Hampshire' },
  { city: 'Pueblo', state: 'Colorado' },
  { city: 'Lakeland', state: 'Florida' },
  { city: 'Pompano Beach', state: 'Florida' },
  { city: 'West Palm Beach', state: 'Florida' },
  { city: 'Antioch', state: 'California' },
  { city: 'Everett', state: 'Washington' },
  { city: 'Downey', state: 'California' },
  { city: 'Lowell', state: 'Massachusetts' },
  { city: 'Centennial', state: 'Colorado' },
  { city: 'Elgin', state: 'Illinois' },
  { city: 'Richmond', state: 'California' },
  { city: 'Peoria', state: 'Illinois' },
  { city: 'Broken Arrow', state: 'Oklahoma' },
  { city: 'Miami Gardens', state: 'Florida' },
  { city: 'Billings', state: 'Montana' },
  { city: 'Jurupa Valley', state: 'California' },
  { city: 'Sandy Springs', state: 'Georgia' },
  { city: 'Gresham', state: 'Oregon' },
  { city: 'Lewisville', state: 'Texas' },
  { city: 'Hillsboro', state: 'Oregon' },
  { city: 'Ventura', state: 'California' },
  { city: 'Greeley', state: 'Colorado' },
  { city: 'Inglewood', state: 'California' },
  { city: 'Waterbury', state: 'Connecticut' },
  { city: 'League City', state: 'Texas' },
  { city: 'Santa Maria', state: 'California' },
  { city: 'Tyler', state: 'Texas' },
  { city: 'Davie', state: 'Florida' },
  { city: 'Lakewood', state: 'New Jersey' },
  { city: 'Daly City', state: 'California' },
  { city: 'Boulder', state: 'Colorado' },
  { city: 'Allen', state: 'Texas' },
  { city: 'West Covina', state: 'California' },
  { city: 'Sparks', state: 'Nevada' },
  { city: 'Wichita Falls', state: 'Texas' },
  { city: 'Green Bay', state: 'Wisconsin' },
  { city: 'San Mateo', state: 'California' },
  { city: 'Norwalk', state: 'California' },
  { city: 'Rialto', state: 'California' },
  { city: 'Las Cruces', state: 'New Mexico' },
  { city: 'Chico', state: 'California' },
  { city: 'El Cajon', state: 'California' },
  { city: 'Burbank', state: 'California' },
  { city: 'South Bend', state: 'Indiana' },
  { city: 'Renton', state: 'Washington' },
  { city: 'Vista', state: 'California' },
  { city: 'Davenport', state: 'Iowa' },
  { city: 'Edinburg', state: 'Texas' },
  { city: 'Tuscaloosa', state: 'Alabama' },
  { city: 'Carmel', state: 'Indiana' },
  { city: 'Spokane Valley', state: 'Washington' },
  { city: 'San Angelo', state: 'Texas' },
  { city: 'Vacaville', state: 'California' },
  { city: 'Clinton', state: 'Michigan' },
  { city: 'Bend', state: 'Oregon' },
  { city: 'Woodbridge', state: 'New Jersey' },
];

// Alabama AL
// Alaska	AK
// Arizona	AZ
// Arkansas	AR
// California	CA
// Colorado	CO
// Connecticut	CT
// Delaware	DE
// District of Columbia	DC
// Florida	FL
// Georgia	GA
// Hawaii	HI
// Idaho	ID
// Illinois	IL
// Indiana	IN
// Iowa	IA
// Kansas	KS
// Kentucky	KY
// Louisiana	LA
// Maine	ME
// Maryland	MD
// Massachusetts	MA
// Michigan	MI
// Minnesota	MN
// Mississippi	MS
// Missouri	MO
// Montana	MT
// Nebraska	NE
// Nevada	NV
// New Hampshire	NH
// New Jersey	NJ
// New Mexico	NM
// New York	NY
// North Carolina	NC
// North Dakota	ND
// Ohio	OH
// Oklahoma	OK
// Oregon	OR
// Pennsylvania	PA
// Rhode Island	RI
// South Carolina	SC
// South Dakota	SD
// Tennessee	TN
// Texas	TX
// Utah	UT
// Vermont	VT
// Virginia	VA
// Washington	WA
// West Virginia	WV
// Wisconsin	WI
// Wyoming	WY
